require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ActionsController do
   context "for creating new board" do
    before do
      get :new
    end
    it { should respond_with(:success) }
  end

end
