require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategoriesController do

  def mock_category(stubs={})
    @mock_category ||= mock_model(Category, stubs).as_null_object
  end

  #def mock_board(stubs={})
   # @mock_board ||= mock_model(Board, stubs).as_null_object    
  #end

  describe "GET show"  do
    it "assigns the requested category as @category" do
      Category.stub(:find).with("37") { mock_category }
   #   Board.stub(:find).with('23') { mock_board }
      get :show, :id => "37",:board_id=>'23'
      assigns(:category).should be(mock_category)
    end
  end

  describe "GET new" do
    it "assigns a new category as @category" do
      Category.stub(:new) { mock_category }
      get :new
      assigns(:category).should be(mock_category)
    end
  end

  describe "GET edit" do
    it "assigns the requested category as @category" do
      Category.stub(:find).with("37") { mock_category }
      get :edit, :id => "37"
      assigns(:category).should be(mock_category)
    end
  end


  describe "DELETE destroy" do
    it "destroys the requested category" do
      Category.stub(:find).with("37") { mock_category }
      mock_category.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the categories list" do
      Category.stub(:find) { mock_category }
      delete :destroy, :id => "1"
      response.should redirect_to(categories_url)
    end
  end

end
